# Generated by Django 3.0.7 on 2020-06-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
